services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.31-latest
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "-l debug"]
    ports:
      - "8080:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  serverA: 
    container_name: serverA
    image: clue/json-server
  serverB: 
    container_name: serverB
    image: clue/json-server